#!/bin/bash

VERSION=$(./build-aux/git-version-gen .tarball-version)
PACKAGE_NAME=ngui_${VERSION}

case $1 in
patch)
    ;;
install_deps)
    git submodule init
    git submodule update
    ;;
configure)
    ./waf configure
    #./waf configure --with-coverage
    ;;
compile)
    ./waf build --notests
    ;;
check)
    ./waf --alltests
    #./waf --lcov-report
    #sh -x ./src/test/coverage.sh -d build/src -o build/check-coverage ./waf --alltests
    ;;
package)
    ./build-aux/git-version-gen .tarball-version > .tarball-version
    git archive --format tar.gz -9 --prefix=${PACKAGE_NAME}/ HEAD > ${PACKAGE_NAME}.tar.gz
    tar zxf ${PACKAGE_NAME}.tar.gz && \
        cp .tarball-version ${PACKAGE_NAME}/.tarball-version && \
        cp -a ${PACKAGE_NAME} ${PACKAGE_NAME}.orig && \
        cd ${PACKAGE_NAME} && \
        ./build-aux/update-debian-changelog debian/changelog $(cat .tarball-version) && \
        debuild -us -uc -sa
    ;;
upload)
    ;;
compile_extra)
    #ldd build/src/qbdevice/qbdevice
    ;;
uninstall_deps)
    ;;
esac
